### ISSUE TITLE
[CONTENT ORGANISATION] Break "Research support" entry into multiple sub-areas

### ISSUE THREAD

**Issue by boyd-nguyen** [QUT-Digital-Observatory/australian_digital_observatory_site#47]

**Comment by Quiet27** [comment]
@boyd-nguyen as discussed, we could also just expand the text on this page (https://www.digitalobservatory.net.au/resources/research-project-support/) to include a list of the types of research support that we have provided.

**Comment by Quiet27** [comment]
Depends on #69 being completed

**Comment by Quiet27** [comment]
Another to do to expand the 'research support' page:

- [ ] Add basic information about consultancy on data governance and ethics

**Comment by Quiet27** [comment]
Depends on https://github.com/QUT-Digital-Observatory/australian_digital_observatory_site/issues/78 (case studies) being completed, since this page will link to the case studies.

Depends on https://github.com/QUT-Digital-Observatory/australian_digital_observatory_site/issues/77 (implement landing pages for each service offering) being completed, since this page will link to each of the three landing pages.
